ERROR 2018-01-31 18:52:30,263 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:32,171 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:33,095 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:33,584 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:34,032 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:34,288 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:34,367 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:34,575 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:34,812 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:34,928 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:35,325 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:35,430 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:35,634 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 18:52:35,799 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 13, in getList
    return obj.load_json("/static/scripts/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 23, in load_json
    with open(infile) as data_file:
IOError: [Errno 2] No such file or directory: '/static/scripts/data.json'
ERROR 2018-01-31 19:27:23,671 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "C:\Python27\lib\site-packages\django\template\utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "C:\Python27\lib\site-packages\django\template\utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 48, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 113, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 2, in <module>
    from predire.static.scripts.recruit_predict import recprec
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 75, in <module>
    c.html_load_json("C:/Users/ktawde/hackathon/autobots/data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 33, in html_load_json
    data[line]['weight'],
IndexError: tuple index out of range
WARNING 2018-01-31 20:15:11,240 - Not Found: /base-score.html
ERROR 2018-01-31 21:47:03,061 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 9, in getList
    return obj.html_load_json("data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 37, in html_load_json
    engine.number_to_words(data[line]['weight']),
TypeError: unbound method number_to_words() must be called with engine instance as first argument (got int instance instead)
ERROR 2018-01-31 21:55:54,763 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 7, in index
    return render_to_response("index.html")
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 9, in getList
    return obj.html_load_json("data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 38, in html_load_json
    self._inf.number_to_words(int(math.ceil(data[line]['weight']) / 10)),
NameError: global name 'math' is not defined
WARNING 2018-02-01 09:47:01,947 - Not Found: /favicon.ico
WARNING 2018-02-01 14:38:35,931 - Not Found: /js/popper.min.js
WARNING 2018-02-01 14:38:37,898 - Not Found: /css/bootstrap.min.css
WARNING 2018-02-01 14:38:37,901 - Not Found: /css/main_dashboard.css
WARNING 2018-02-01 14:38:37,904 - Not Found: /js/jquery-3.2.1.slim.min.js
WARNING 2018-02-01 14:38:37,921 - Not Found: /js/popper.min.js
WARNING 2018-02-01 14:38:37,944 - Not Found: /js/main.js
WARNING 2018-02-01 14:38:37,956 - Not Found: /js/bootstrap.min.js
WARNING 2018-02-01 14:38:37,956 - Not Found: /img/incedo-header-logo.png
WARNING 2018-02-01 14:38:37,982 - Not Found: /js/popper.min.js
WARNING 2018-02-01 14:38:37,996 - Not Found: /js/bootstrap.min.js
WARNING 2018-02-01 14:39:47,619 - Not Found: /tabular.html
WARNING 2018-02-01 14:40:29,065 - Not Found: /index.html
ERROR 2018-02-01 15:16:09,184 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 17, in dashboard
    dict[val]= request.GET.get(val)
TypeError: 'tuple' object does not support item assignment
ERROR 2018-02-01 15:16:12,868 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 17, in dashboard
    dict[val]= request.GET.get(val)
TypeError: 'tuple' object does not support item assignment
ERROR 2018-02-01 15:16:31,992 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 17, in dashboard
    dict[val]= request.GET.get(val)
TypeError: 'tuple' object does not support item assignment
ERROR 2018-02-01 15:31:04,484 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 15, in dashboard
    switch = obj.get_switch()
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 32, in get_switch
    'mapping']]
TypeError: coercing to Unicode: need string or buffer, int found
ERROR 2018-02-01 15:32:03,967 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 15, in dashboard
    switch = obj.get_switch()
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 32, in get_switch
    'mapping']]
TypeError: coercing to Unicode: need string or buffer, int found
ERROR 2018-02-01 15:32:21,523 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 15, in dashboard
    switch = obj.get_switch()
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 32, in get_switch
    'mapping']]
TypeError: coercing to Unicode: need string or buffer, int found
ERROR 2018-02-01 15:49:32,858 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 21, in dashboard
    calc_weight = obj.calc_weight_switch(dict)
TypeError: calc_weight_switch() takes exactly 1 argument (2 given)
INFO 2018-02-01 15:49:51,427 - Calculating weight for id None
ERROR 2018-02-01 15:49:51,428 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 21, in dashboard
    calc_weight = obj.calc_weight_switch(dict)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 82, in calc_weight_switch
    self._weight += weight
TypeError: unsupported operand type(s) for +=: 'int' and 'unicode'
INFO 2018-02-01 15:50:13,243 - Calculating weight for id None
ERROR 2018-02-01 15:50:13,247 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 21, in dashboard
    calc_weight = obj.calc_weight_switch(dict)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 83, in calc_weight_switch
    self.write_db()
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 52, in write_db
    data[self._recid]["weight"] = self._weight
KeyError: None
INFO 2018-02-01 15:50:39,670 - Calculating weight for id None
ERROR 2018-02-01 15:50:39,671 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 21, in dashboard
    calc_weight = obj.calc_weight_switch(dict)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 83, in calc_weight_switch
    self.write_db()
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 52, in write_db
    data[self._recid]["weight"] = self._weight
KeyError: None
INFO 2018-02-01 15:50:40,670 - Calculating weight for id None
ERROR 2018-02-01 15:50:40,670 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 21, in dashboard
    calc_weight = obj.calc_weight_switch(dict)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 83, in calc_weight_switch
    self.write_db()
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 52, in write_db
    data[self._recid]["weight"] = self._weight
KeyError: None
INFO 2018-02-01 15:50:41,529 - Calculating weight for id None
ERROR 2018-02-01 15:50:41,530 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 21, in dashboard
    calc_weight = obj.calc_weight_switch(dict)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 83, in calc_weight_switch
    self.write_db()
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 52, in write_db
    data[self._recid]["weight"] = self._weight
KeyError: None
INFO 2018-02-01 15:52:26,483 - Calculating weight for id None
INFO 2018-02-01 15:52:44,881 - Calculating weight for id None
INFO 2018-02-01 15:52:46,071 - Calculating weight for id None
INFO 2018-02-01 15:52:51,456 - Calculating weight for id None
ERROR 2018-02-01 15:52:51,463 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 21, in dashboard
    calc_weight = obj.calc_weight_switch(dict)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 84, in calc_weight_switch
    self.write_db()
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 52, in write_db
    data[self._recid]["weight"] = self._weight
KeyError: None
INFO 2018-02-01 15:52:56,503 - Calculating weight for id None
INFO 2018-02-01 15:53:04,556 - Calculating weight for id None
INFO 2018-02-01 15:53:05,920 - Calculating weight for id None
INFO 2018-02-01 15:53:16,220 - Calculating weight for id None
INFO 2018-02-01 15:53:50,898 - Calculating weight for id None
INFO 2018-02-01 15:54:07,098 - Calculating weight for id None
INFO 2018-02-01 15:54:15,219 - Calculating weight for id None
INFO 2018-02-01 15:54:21,141 - Calculating weight for id None
INFO 2018-02-01 15:54:28,009 - Calculating weight for id None
INFO 2018-02-01 15:54:30,627 - Calculating weight for id None
INFO 2018-02-01 15:54:49,532 - Calculating weight for id None
INFO 2018-02-01 15:54:54,088 - Calculating weight for id None
INFO 2018-02-01 15:54:59,038 - Calculating weight for id None
INFO 2018-02-01 16:01:59,404 - Calculating weight for id None
INFO 2018-02-01 16:04:40,283 - Calculating weight for id None
INFO 2018-02-01 16:04:59,430 - Calculating weight for id None
INFO 2018-02-01 17:44:46,822 - Calculating weight for id None
INFO 2018-02-01 17:47:10,966 - Calculating weight for id None
INFO 2018-02-01 17:47:40,963 - Calculating weight for id None
ERROR 2018-02-01 17:47:52,947 - Internal Server Error: /index.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 10, in index
    return render_to_response("index.html", {'name':name})
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 9, in getList
    return obj.html_load_json("data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 36, in html_load_json
    data = self.load_json(infile)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 27, in load_json
    data = json.load(data_file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ERROR 2018-02-01 17:47:55,397 - Internal Server Error: /index.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 10, in index
    return render_to_response("index.html", {'name':name})
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 9, in getList
    return obj.html_load_json("data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 36, in html_load_json
    data = self.load_json(infile)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 27, in load_json
    data = json.load(data_file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
INFO 2018-02-01 17:47:57,803 - Calculating weight for id None
ERROR 2018-02-01 17:48:01,105 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 10, in index
    return render_to_response("index.html", {'name':name})
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 9, in getList
    return obj.html_load_json("data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 36, in html_load_json
    data = self.load_json(infile)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 27, in load_json
    data = json.load(data_file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
INFO 2018-02-01 17:48:24,697 - Calculating weight for id None
INFO 2018-02-01 17:48:27,315 - Calculating weight for id None
ERROR 2018-02-01 17:49:00,979 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 10, in index
    return render_to_response("index.html", {'name':name})
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 9, in getList
    return obj.html_load_json("data.json")
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 36, in html_load_json
    data = self.load_json(infile)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 27, in load_json
    data = json.load(data_file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
INFO 2018-02-01 17:49:51,421 - Calculating weight for id None
INFO 2018-02-01 17:55:28,193 - Calculating weight for id None
WARNING 2018-02-01 18:04:37,125 - Not Found: /favicon.ico
WARNING 2018-02-01 18:16:11,312 - Not Found: /favicon.ico
INFO 2018-02-01 18:17:43,915 - Calculating weight for id None
INFO 2018-02-01 18:46:42,341 - Calculating weight for id None
INFO 2018-02-01 18:47:17,849 - Calculating weight for id None
INFO 2018-02-01 18:47:29,933 - Calculating weight for id None
INFO 2018-02-01 18:47:37,286 - Calculating weight for id None
INFO 2018-02-01 18:47:42,701 - Calculating weight for id None
INFO 2018-02-01 18:47:47,890 - Calculating weight for id None
INFO 2018-02-01 18:48:05,286 - Calculating weight for id None
INFO 2018-02-01 18:48:22,164 - Calculating weight for id None
INFO 2018-02-01 18:54:46,496 - Calculating weight for id None
INFO 2018-02-01 18:55:49,453 - Calculating weight for id None
INFO 2018-02-01 18:58:22,203 - Calculating weight for id None
INFO 2018-02-01 18:59:26,194 - Calculating weight for id None
INFO 2018-02-01 18:59:33,329 - Calculating weight for id None
INFO 2018-02-01 18:59:54,474 - Calculating weight for id None
INFO 2018-02-01 19:00:25,012 - Calculating weight for id None
INFO 2018-02-01 19:00:41,470 - Calculating weight for id None
INFO 2018-02-01 19:00:51,733 - Calculating weight for id None
INFO 2018-02-01 19:04:16,654 - Calculating weight for id None
INFO 2018-02-01 19:08:12,186 - Calculating weight for id None
INFO 2018-02-01 19:08:20,188 - Calculating weight for id None
INFO 2018-02-01 19:08:28,082 - Calculating weight for id None
INFO 2018-02-01 19:08:37,144 - Calculating weight for id None
INFO 2018-02-01 19:08:42,681 - Calculating weight for id None
INFO 2018-02-01 19:09:34,183 - Calculating weight for id None
INFO 2018-02-01 19:09:55,430 - Calculating weight for id None
INFO 2018-02-01 19:23:19,526 - Calculating weight for id None
INFO 2018-02-01 19:26:21,217 - Calculating weight for id None
INFO 2018-02-01 19:26:23,398 - Calculating weight for id None
INFO 2018-02-01 19:26:25,940 - Calculating weight for id None
INFO 2018-02-01 19:26:28,915 - Calculating weight for id None
INFO 2018-02-01 19:26:32,436 - Calculating weight for id None
INFO 2018-02-01 19:26:39,802 - Calculating weight for id None
INFO 2018-02-01 19:26:47,535 - Calculating weight for id None
INFO 2018-02-01 19:26:57,407 - Calculating weight for id None
INFO 2018-02-01 19:27:32,302 - Calculating weight for id None
INFO 2018-02-01 19:27:36,855 - Calculating weight for id None
INFO 2018-02-01 19:28:55,413 - Calculating weight for id None
INFO 2018-02-01 19:29:59,822 - Calculating weight for id None
INFO 2018-02-01 19:30:01,733 - Calculating weight for id None
INFO 2018-02-01 19:30:05,313 - Calculating weight for id None
INFO 2018-02-01 19:37:17,615 - Calculating weight for id None
INFO 2018-02-01 19:37:21,979 - Calculating weight for id None
INFO 2018-02-01 19:37:24,178 - Calculating weight for id None
INFO 2018-02-01 19:38:23,815 - Calculating weight for id None
INFO 2018-02-01 19:51:55,421 - Calculating weight for id None
INFO 2018-02-01 19:52:02,421 - Calculating weight for id None
INFO 2018-02-01 19:54:07,884 - Calculating weight for id None
INFO 2018-02-01 19:54:21,917 - Calculating weight for id None
INFO 2018-02-01 19:54:49,217 - Calculating weight for id None
INFO 2018-02-01 20:08:15,913 - Calculating weight for id None
INFO 2018-02-01 20:10:44,944 - Calculating weight for id None
INFO 2018-02-01 20:12:37,543 - Calculating weight for id None
ERROR 2018-02-01 20:12:37,552 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 29, in dashboard
    {'weight':calc_weight, 'id':id}
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python27\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 486, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '-switch' from 'morepackage-switch'
INFO 2018-02-01 20:13:56,897 - Calculating weight for id None
ERROR 2018-02-01 20:13:56,910 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 29, in dashboard
    {'weight-abc':calc_weight, 'id':id}
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python27\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 486, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '-abc' from 'weight-abc'
INFO 2018-02-01 20:14:06,835 - Calculating weight for id None
ERROR 2018-02-01 20:21:56,653 - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 10, in index
    return render_to_response("index.html", {'name':name})
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python27\lib\site-packages\django\template\library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\templatetags\tags.py", line 8, in getList
    obj = recprec()
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 14, in __init__
    self._mapping = self.load_json('mapping.json')
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 30, in load_json
    data = json.load(data_file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
INFO 2018-02-01 20:22:34,101 - Calculating weight for id None
INFO 2018-02-01 20:23:13,032 - Calculating weight for id None
INFO 2018-02-01 20:23:14,489 - Calculating weight for id None
INFO 2018-02-01 20:23:14,937 - Calculating weight for id None
INFO 2018-02-01 20:23:15,089 - Calculating weight for id None
INFO 2018-02-01 20:23:53,030 - Calculating weight for id None
INFO 2018-02-01 20:23:53,903 - Calculating weight for id None
INFO 2018-02-01 20:24:13,492 - Calculating weight for id None
INFO 2018-02-01 20:24:34,240 - Calculating weight for id None
INFO 2018-02-01 20:25:13,582 - Calculating weight for id None
INFO 2018-02-01 20:25:42,201 - Calculating weight for id None
ERROR 2018-02-01 20:25:42,203 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 28, in dashboard
    {id_mapping}
TypeError: unhashable type: 'dict'
INFO 2018-02-01 20:27:06,270 - Calculating weight for id None
INFO 2018-02-01 20:27:24,400 - Calculating weight for id None
INFO 2018-02-01 20:27:53,680 - Calculating weight for id None
INFO 2018-02-01 20:28:23,674 - Calculating weight for id None
INFO 2018-02-01 20:28:35,986 - Calculating weight for id None
INFO 2018-02-01 20:28:57,789 - Calculating weight for id None
INFO 2018-02-01 20:29:20,986 - Calculating weight for id None
INFO 2018-02-01 20:34:23,654 - Calculating weight for id None
INFO 2018-02-01 20:34:26,257 - Calculating weight for id None
ERROR 2018-02-01 20:34:26,257 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    return self._weight, dict(self._data[id]["mapping"])
KeyError: None
INFO 2018-02-01 20:34:48,217 - Calculating weight for id None
ERROR 2018-02-01 20:34:48,217 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    return self._weight, dict(self._data[id]["mapping"])
KeyError: None
INFO 2018-02-01 20:34:55,292 - Calculating weight for id None
ERROR 2018-02-01 20:34:55,292 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    return self._weight, dict(self._data[id]["mapping"])
KeyError: None
INFO 2018-02-01 20:35:06,247 - Calculating weight for id None
ERROR 2018-02-01 20:35:06,247 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    return self._weight, dict(self._data[id]["mapping"])
KeyError: None
INFO 2018-02-01 20:35:17,901 - Calculating weight for id None
INFO 2018-02-01 20:35:21,398 - Calculating weight for id None
ERROR 2018-02-01 20:35:21,398 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    return self._weight, dict(self._data[id]["mapping"])
KeyError: None
INFO 2018-02-01 20:35:34,773 - Calculating weight for id None
INFO 2018-02-01 20:38:37,273 - Calculating weight for id None
INFO 2018-02-01 20:41:09,242 - Calculating weight for id None
ERROR 2018-02-01 20:41:09,242 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    return self._weight, dict(self._data[id]["name"]), dict(self._data[id][
ValueError: dictionary update sequence element #0 has length 1; 2 is required
INFO 2018-02-01 20:41:53,834 - Calculating weight for id None
INFO 2018-02-01 20:42:12,956 - Calculating weight for id None
INFO 2018-02-01 20:42:16,967 - Calculating weight for id None
INFO 2018-02-01 20:42:20,232 - Calculating weight for id None
INFO 2018-02-01 20:42:23,848 - Calculating weight for id None
INFO 2018-02-01 20:42:26,770 - Calculating weight for id None
INFO 2018-02-01 20:42:44,707 - Calculating weight for id None
INFO 2018-02-01 20:42:47,341 - Calculating weight for id None
ERROR 2018-02-01 20:42:47,342 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    return self._weight, self._data[id]["name"], dict(self._data[id]["mapping"])
KeyError: None
INFO 2018-02-01 20:43:11,520 - Calculating weight for id None
ERROR 2018-02-01 20:43:11,520 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    return self._weight, self._data[id]["name"], dict(self._data[id]["mapping"])
KeyError: None
INFO 2018-02-01 20:44:36,365 - Calculating weight for id None
ERROR 2018-02-01 20:44:36,365 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    return self._weight, self._data[id]["name"], dict(self._data[id]["mapping"])
KeyError: None
INFO 2018-02-01 20:45:06,706 - Calculating weight for id None
INFO 2018-02-01 20:45:09,346 - Calculating weight for id None
INFO 2018-02-01 20:45:12,776 - Calculating weight for id None
ERROR 2018-02-01 20:45:12,776 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    return self._weight, self._data[id]["name"], dict(self._data[id]["mapping"])
KeyError: None
INFO 2018-02-01 20:46:06,440 - Calculating weight for id None
ERROR 2018-02-01 20:46:06,440 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    print self._data[id]["name"]
KeyError: None
INFO 2018-02-01 20:46:15,279 - Calculating weight for id None
ERROR 2018-02-01 20:46:15,279 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    print self._data[id]["name"]
KeyError: None
INFO 2018-02-01 20:47:02,690 - Calculating weight for id None
INFO 2018-02-01 20:48:03,976 - Calculating weight for id None
INFO 2018-02-01 20:48:13,431 - Calculating weight for id None
INFO 2018-02-01 20:48:18,278 - Calculating weight for id None
ERROR 2018-02-01 20:48:18,278 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    print self._data[id]["name"]
KeyError: u''
INFO 2018-02-01 20:49:09,094 - Calculating weight for id None
ERROR 2018-02-01 20:49:09,095 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    print self._data[id]["name"]
KeyError: u''
INFO 2018-02-01 20:49:14,283 - Calculating weight for id None
INFO 2018-02-01 20:49:16,023 - Calculating weight for id None
INFO 2018-02-01 21:10:26,323 - Calculating weight for id None
INFO 2018-02-01 21:10:29,088 - Calculating weight for id None
INFO 2018-02-01 21:10:31,980 - Calculating weight for id None
INFO 2018-02-01 21:10:36,473 - Calculating weight for id None
INFO 2018-02-01 21:10:39,134 - Calculating weight for id None
INFO 2018-02-01 21:13:55,624 - Calculating weight for id None
INFO 2018-02-01 21:13:57,002 - Calculating weight for id None
INFO 2018-02-01 21:14:00,346 - Calculating weight for id None
INFO 2018-02-01 21:14:03,171 - Calculating weight for id None
INFO 2018-02-01 21:14:10,782 - Calculating weight for id None
INFO 2018-02-01 21:14:31,506 - Calculating weight for id None
INFO 2018-02-01 21:14:34,594 - Calculating weight for id None
INFO 2018-02-01 21:14:56,286 - Calculating weight for id None
INFO 2018-02-01 21:17:23,257 - Calculating weight for id None
INFO 2018-02-01 21:17:27,155 - Calculating weight for id None
INFO 2018-02-01 21:17:28,701 - Calculating weight for id None
INFO 2018-02-01 21:17:47,756 - Calculating weight for id None
INFO 2018-02-01 21:17:51,374 - Calculating weight for id None
INFO 2018-02-01 21:17:55,403 - Calculating weight for id None
INFO 2018-02-01 21:21:45,673 - Calculating weight for id None
INFO 2018-02-01 21:23:05,421 - Calculating weight for id None
ERROR 2018-02-01 21:23:05,436 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    self.write_db(id, dict(self._data[id]["mapping"]))
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 55, in write_db
    data[self._recid]["weight"] = self._weight
KeyError: None
INFO 2018-02-01 21:23:42,516 - Calculating weight for id None
ERROR 2018-02-01 21:23:42,519 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    self.write_db(id, dict(self._data[id]["mapping"]))
TypeError: write_db() takes exactly 1 argument (3 given)
INFO 2018-02-01 21:23:47,081 - Calculating weight for id None
ERROR 2018-02-01 21:23:47,085 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 89, in calc_weight_switch
    self.write_db(id, dict(self._data[id]["mapping"]))
TypeError: write_db() takes exactly 1 argument (3 given)
INFO 2018-02-01 21:23:59,065 - Calculating weight for id None
INFO 2018-02-01 21:24:00,644 - Calculating weight for id None
INFO 2018-02-01 21:27:39,174 - Calculating weight for id None
ERROR 2018-02-01 21:27:39,184 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 23, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 88, in calc_weight_switch
    self.write_db(id, dict(self._data[id]["mapping"]))
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 63, in write_db
    data[self._recid]["name"],
KeyError: None
INFO 2018-02-01 21:28:01,970 - Calculating weight for id None
INFO 2018-02-01 21:28:01,982 - Updated weight for [2 : Sagar Jagtap] to 102
INFO 2018-02-01 21:28:05,381 - Calculating weight for id None
INFO 2018-02-01 21:28:05,392 - Updated weight for [2 : Sagar Jagtap] to 105
INFO 2018-02-01 21:28:46,201 - Calculating weight for id None
INFO 2018-02-01 21:28:46,217 - Updated weight for [2 : Sagar Jagtap] to 105
INFO 2018-02-01 21:28:55,622 - Calculating weight for id None
INFO 2018-02-01 21:28:55,683 - Updated weight for [2 : Sagar Jagtap] to 105
INFO 2018-02-01 21:29:00,928 - Calculating weight for id None
INFO 2018-02-01 21:29:01,012 - Updated weight for [2 : Sagar Jagtap] to 112
INFO 2018-02-01 21:29:20,663 - Calculating weight for id None
INFO 2018-02-01 21:29:20,668 - Updated weight for [2 : Sagar Jagtap] to 105
INFO 2018-02-01 21:31:05,792 - Calculating weight for id None
INFO 2018-02-01 21:31:05,801 - Updated weight for [2 : Sagar Jagtap] to 102
INFO 2018-02-01 21:31:32,700 - Calculating weight for id None
INFO 2018-02-01 21:31:32,710 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-01 21:31:40,186 - Calculating weight for id None
INFO 2018-02-01 21:31:40,210 - Updated weight for [2 : Sagar Jagtap] to 100
INFO 2018-02-01 21:35:46,819 - Calculating weight for id None
INFO 2018-02-01 21:35:46,828 - Updated weight for [2 : Sagar Jagtap] to 117
INFO 2018-02-01 21:39:59,831 - Calculating weight for id None
INFO 2018-02-01 21:39:59,835 - Updated weight for [2 : Sagar Jagtap] to 102
INFO 2018-02-01 21:41:00,915 - Calculating weight for id None
INFO 2018-02-01 21:41:00,923 - Updated weight for [2 : Sagar Jagtap] to 105
INFO 2018-02-01 21:43:37,476 - Calculating weight for id None
INFO 2018-02-01 21:43:37,483 - Updated weight for [2 : Sagar Jagtap] to 105
INFO 2018-02-01 21:44:48,463 - Calculating weight for id None
ERROR 2018-02-01 21:44:48,463 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 24, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 86, in calc_weight_switch
    for map in self._data[id]["mapping"]:
RuntimeError: dictionary changed size during iteration
INFO 2018-02-01 21:45:37,246 - Calculating weight for id None
INFO 2018-02-01 21:45:37,313 - Updated weight for [2 : Sagar Jagtap] to 105
INFO 2018-02-01 21:45:40,456 - Calculating weight for id None
INFO 2018-02-01 21:45:40,463 - Updated weight for [2 : Sagar Jagtap] to 120
INFO 2018-02-01 21:45:43,388 - Calculating weight for id None
INFO 2018-02-01 21:45:43,391 - Updated weight for [2 : Sagar Jagtap] to 120
INFO 2018-02-01 21:45:46,147 - Calculating weight for id None
INFO 2018-02-01 21:45:46,155 - Updated weight for [2 : Sagar Jagtap] to 90
INFO 2018-02-01 21:46:05,334 - Calculating weight for id None
INFO 2018-02-01 21:46:05,344 - Updated weight for [2 : Sagar Jagtap] to 75
INFO 2018-02-01 21:46:07,855 - Calculating weight for id None
INFO 2018-02-01 21:46:07,859 - Updated weight for [2 : Sagar Jagtap] to 75
INFO 2018-02-01 21:46:33,957 - Calculating weight for id None
INFO 2018-02-01 21:46:33,964 - Updated weight for [2 : Sagar Jagtap] to 75
INFO 2018-02-01 21:46:36,312 - Calculating weight for id None
INFO 2018-02-01 21:46:36,321 - Updated weight for [2 : Sagar Jagtap] to 72
INFO 2018-02-01 21:46:38,730 - Calculating weight for id None
INFO 2018-02-01 21:46:38,740 - Updated weight for [2 : Sagar Jagtap] to 82
INFO 2018-02-01 21:46:40,793 - Calculating weight for id None
INFO 2018-02-01 21:46:40,805 - Updated weight for [2 : Sagar Jagtap] to 72
INFO 2018-02-01 21:46:53,418 - Calculating weight for id None
INFO 2018-02-01 21:46:53,430 - Updated weight for [2 : Sagar Jagtap] to 87
INFO 2018-02-01 21:46:59,141 - Calculating weight for id None
INFO 2018-02-01 21:46:59,151 - Updated weight for [2 : Sagar Jagtap] to 75
INFO 2018-02-01 21:47:01,661 - Calculating weight for id None
INFO 2018-02-01 21:47:01,668 - Updated weight for [2 : Sagar Jagtap] to 72
INFO 2018-02-01 21:47:04,266 - Calculating weight for id None
INFO 2018-02-01 21:47:04,273 - Updated weight for [2 : Sagar Jagtap] to 57
INFO 2018-02-01 21:47:10,266 - Calculating weight for id None
INFO 2018-02-01 21:47:10,272 - Updated weight for [2 : Sagar Jagtap] to 75
INFO 2018-02-01 21:47:13,763 - Calculating weight for id None
INFO 2018-02-01 21:47:13,770 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 21:47:15,526 - Calculating weight for id None
INFO 2018-02-01 21:47:15,533 - Updated weight for [3 : Shruti Agarawal] to 75
INFO 2018-02-01 21:54:53,596 - Calculating weight for id None
INFO 2018-02-01 21:54:53,621 - Updated weight for [3 : Shruti Agarawal] to 75
INFO 2018-02-01 21:54:56,006 - Calculating weight for id None
INFO 2018-02-01 21:54:56,015 - Updated weight for [3 : Shruti Agarawal] to 75
INFO 2018-02-01 22:00:23,016 - Calculating weight for id None
INFO 2018-02-01 22:00:23,025 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 22:00:26,282 - Calculating weight for id None
INFO 2018-02-01 22:00:26,289 - Updated weight for [3 : Shruti Agarawal] to 130
INFO 2018-02-01 22:00:29,641 - Calculating weight for id None
INFO 2018-02-01 22:00:29,648 - Updated weight for [3 : Shruti Agarawal] to 115
INFO 2018-02-01 22:00:32,252 - Calculating weight for id None
INFO 2018-02-01 22:00:32,260 - Updated weight for [3 : Shruti Agarawal] to 90
INFO 2018-02-01 22:00:49,799 - Calculating weight for id None
INFO 2018-02-01 22:00:49,809 - Updated weight for [3 : Shruti Agarawal] to 75
INFO 2018-02-01 22:00:52,286 - Calculating weight for id None
INFO 2018-02-01 22:00:52,295 - Updated weight for [3 : Shruti Agarawal] to 72
INFO 2018-02-01 22:00:54,829 - Calculating weight for id None
INFO 2018-02-01 22:00:54,838 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:00:57,802 - Calculating weight for id None
INFO 2018-02-01 22:00:57,809 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 22:01:01,461 - Calculating weight for id None
INFO 2018-02-01 22:01:01,467 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-01 22:01:03,671 - Calculating weight for id None
INFO 2018-02-01 22:01:03,678 - Updated weight for [1 : Kalpesh Tawde] to 85
INFO 2018-02-01 22:01:07,197 - Calculating weight for id None
INFO 2018-02-01 22:01:07,204 - Updated weight for [2 : Sagar Jagtap] to 100
INFO 2018-02-01 22:01:09,700 - Calculating weight for id None
INFO 2018-02-01 22:01:09,706 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-01 22:01:25,523 - Calculating weight for id None
INFO 2018-02-01 22:01:25,528 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 22:01:28,384 - Calculating weight for id None
INFO 2018-02-01 22:01:28,392 - Updated weight for [3 : Shruti Agarawal] to 97
INFO 2018-02-01 22:01:34,026 - Calculating weight for id None
INFO 2018-02-01 22:01:34,030 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 22:01:37,773 - Calculating weight for id None
INFO 2018-02-01 22:01:37,776 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 22:02:09,003 - Calculating weight for id None
INFO 2018-02-01 22:02:09,013 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:02:11,779 - Calculating weight for id None
INFO 2018-02-01 22:02:11,789 - Updated weight for [6 : Pratyush] to 110
INFO 2018-02-01 22:02:14,588 - Calculating weight for id None
INFO 2018-02-01 22:02:14,599 - Updated weight for [6 : Pratyush] to 107
INFO 2018-02-01 22:03:05,539 - Calculating weight for id None
INFO 2018-02-01 22:03:05,549 - Updated weight for [5 : Gaurav Gupta] to 100
INFO 2018-02-01 22:03:23,700 - Calculating weight for id None
INFO 2018-02-01 22:03:23,704 - Updated weight for [5 : Gaurav Gupta] to 100
INFO 2018-02-01 22:03:57,621 - Calculating weight for id None
INFO 2018-02-01 22:03:57,630 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:04:01,015 - Calculating weight for id None
INFO 2018-02-01 22:04:01,023 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:06:42,503 - Calculating weight for id None
INFO 2018-02-01 22:06:42,509 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:20:02,153 - Calculating weight for id None
INFO 2018-02-01 22:20:02,391 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:21:22,322 - Calculating weight for id None
INFO 2018-02-01 22:21:22,328 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:21:30,029 - Calculating weight for id None
INFO 2018-02-01 22:21:30,033 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:21:34,638 - Calculating weight for id None
INFO 2018-02-01 22:21:34,648 - Updated weight for [6 : Pratyush] to 110
INFO 2018-02-01 22:21:38,006 - Calculating weight for id None
INFO 2018-02-01 22:21:38,009 - Updated weight for [6 : Pratyush] to 110
INFO 2018-02-01 22:21:39,381 - Calculating weight for id None
INFO 2018-02-01 22:21:39,384 - Updated weight for [6 : Pratyush] to 110
INFO 2018-02-01 22:23:17,604 - Calculating weight for id None
ERROR 2018-02-01 22:23:17,604 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 27, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 87, in calc_weight_switch
    for mapping in self._data[id]["mapping"]:
KeyError: u''
INFO 2018-02-01 22:24:47,960 - Calculating weight for id None
INFO 2018-02-01 22:24:47,967 - Updated weight for [5 : Gaurav Gupta] to 97
INFO 2018-02-01 22:24:51,562 - Calculating weight for id None
INFO 2018-02-01 22:24:51,572 - Updated weight for [5 : Gaurav Gupta] to 127
INFO 2018-02-01 22:24:56,503 - Calculating weight for id None
INFO 2018-02-01 22:24:56,513 - Updated weight for [5 : Gaurav Gupta] to 112
INFO 2018-02-01 22:24:58,743 - Calculating weight for id None
INFO 2018-02-01 22:24:58,756 - Updated weight for [5 : Gaurav Gupta] to 102
INFO 2018-02-01 22:25:01,061 - Calculating weight for id None
INFO 2018-02-01 22:25:01,069 - Updated weight for [5 : Gaurav Gupta] to 132
INFO 2018-02-01 22:25:04,924 - Calculating weight for id None
INFO 2018-02-01 22:25:04,930 - Updated weight for [5 : Gaurav Gupta] to 117
INFO 2018-02-01 22:25:07,148 - Calculating weight for id None
INFO 2018-02-01 22:25:07,160 - Updated weight for [5 : Gaurav Gupta] to 120
INFO 2018-02-01 22:26:11,533 - Calculating weight for id None
INFO 2018-02-01 22:26:11,543 - Updated weight for [5 : Gaurav Gupta] to 95
INFO 2018-02-01 22:26:14,460 - Calculating weight for id None
INFO 2018-02-01 22:26:14,464 - Updated weight for [5 : Gaurav Gupta] to 95
INFO 2018-02-01 22:26:17,543 - Calculating weight for id None
INFO 2018-02-01 22:26:17,555 - Updated weight for [5 : Gaurav Gupta] to 80
INFO 2018-02-01 22:26:23,417 - Calculating weight for id None
INFO 2018-02-01 22:26:23,424 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:26:31,296 - Calculating weight for id None
INFO 2018-02-01 22:26:31,302 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:26:34,217 - Calculating weight for id None
INFO 2018-02-01 22:26:34,227 - Updated weight for [4 : Mahesh Waikar] to 107
INFO 2018-02-01 22:26:37,242 - Calculating weight for id None
INFO 2018-02-01 22:26:37,252 - Updated weight for [4 : Mahesh Waikar] to 137
INFO 2018-02-01 22:26:39,578 - Calculating weight for id None
INFO 2018-02-01 22:26:39,588 - Updated weight for [4 : Mahesh Waikar] to 112
INFO 2018-02-01 22:28:37,997 - Calculating weight for id None
INFO 2018-02-01 22:28:38,003 - Updated weight for [4 : Mahesh Waikar] to 112
INFO 2018-02-01 22:28:42,088 - Calculating weight for id None
INFO 2018-02-01 22:28:42,092 - Updated weight for [4 : Mahesh Waikar] to 107
INFO 2018-02-01 22:28:44,723 - Calculating weight for id None
INFO 2018-02-01 22:28:44,726 - Updated weight for [4 : Mahesh Waikar] to 107
INFO 2018-02-01 22:28:46,453 - Calculating weight for id None
INFO 2018-02-01 22:28:46,461 - Updated weight for [4 : Mahesh Waikar] to 92
INFO 2018-02-01 22:28:53,223 - Calculating weight for id None
INFO 2018-02-01 22:28:53,233 - Updated weight for [4 : Mahesh Waikar] to 97
INFO 2018-02-01 22:28:56,811 - Calculating weight for id None
INFO 2018-02-01 22:28:56,819 - Updated weight for [4 : Mahesh Waikar] to 67
INFO 2018-02-01 22:28:59,197 - Calculating weight for id None
INFO 2018-02-01 22:28:59,203 - Updated weight for [4 : Mahesh Waikar] to 57
INFO 2018-02-01 22:29:00,984 - Calculating weight for id None
INFO 2018-02-01 22:29:00,999 - Updated weight for [4 : Mahesh Waikar] to 60
INFO 2018-02-01 22:29:35,536 - Calculating weight for id None
INFO 2018-02-01 22:29:35,545 - Updated weight for [5 : Gaurav Gupta] to 137
ERROR 2018-02-01 22:29:48,670 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 32, in dashboard
    id_mapping["name"] = id_name
UnboundLocalError: local variable 'id_name' referenced before assignment
INFO 2018-02-01 22:30:09,042 - Calculating weight for id None
INFO 2018-02-01 22:30:09,062 - Updated weight for [5 : Gaurav Gupta] to 115
INFO 2018-02-01 22:30:11,260 - Calculating weight for id None
INFO 2018-02-01 22:30:11,269 - Updated weight for [5 : Gaurav Gupta] to 115
INFO 2018-02-01 22:30:24,813 - Calculating weight for id None
INFO 2018-02-01 22:30:24,825 - Updated weight for [4 : Mahesh Waikar] to 67
INFO 2018-02-01 22:30:53,641 - Calculating weight for id None
INFO 2018-02-01 22:30:53,670 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:30:58,140 - Calculating weight for id None
INFO 2018-02-01 22:30:58,148 - Updated weight for [4 : Mahesh Waikar] to 92
INFO 2018-02-01 22:32:29,732 - Calculating weight for id None
INFO 2018-02-01 22:32:29,740 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:32:31,513 - Calculating weight for id None
INFO 2018-02-01 22:32:31,516 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:32:33,681 - Calculating weight for id None
INFO 2018-02-01 22:32:33,690 - Updated weight for [6 : Pratyush] to 97
INFO 2018-02-01 22:32:34,891 - Calculating weight for id None
INFO 2018-02-01 22:32:34,898 - Updated weight for [6 : Pratyush] to 97
INFO 2018-02-01 22:32:37,022 - Calculating weight for id None
INFO 2018-02-01 22:32:37,029 - Updated weight for [6 : Pratyush] to 82
INFO 2018-02-01 22:32:40,220 - Calculating weight for id None
INFO 2018-02-01 22:32:40,223 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:33:30,427 - Calculating weight for id None
INFO 2018-02-01 22:33:30,436 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:33:51,302 - Calculating weight for id None
INFO 2018-02-01 22:33:51,306 - Updated weight for [5 : Gaurav Gupta] to 100
INFO 2018-02-01 22:35:08,381 - Calculating weight for id None
INFO 2018-02-01 22:35:08,384 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:35:14,773 - Calculating weight for id None
INFO 2018-02-01 22:35:14,778 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 22:35:33,516 - Calculating weight for id None
INFO 2018-02-01 22:35:33,519 - Updated weight for [5 : Gaurav Gupta] to 100
INFO 2018-02-01 22:35:42,213 - Calculating weight for id None
INFO 2018-02-01 22:35:42,265 - Updated weight for [4 : Mahesh Waikar] to 100
ERROR 2018-02-01 22:38:28,198 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 22, in dashboard
    print req.META['HTTP_REFERER']
KeyError: u'HTTP_REFERER'
ERROR 2018-02-01 22:38:40,164 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 22, in dashboard
    print req.META['HTTP_REFERER']
KeyError: u'HTTP_REFERER'
INFO 2018-02-01 22:42:57,275 - Calculating weight for id None
INFO 2018-02-01 22:42:57,282 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:43:02,176 - Calculating weight for id None
INFO 2018-02-01 22:43:02,177 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 22:43:06,256 - Calculating weight for id None
INFO 2018-02-01 22:43:06,262 - Updated weight for [2 : Sagar Jagtap] to 100
INFO 2018-02-01 22:43:10,267 - Calculating weight for id None
INFO 2018-02-01 22:43:10,272 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:43:13,595 - Calculating weight for id None
INFO 2018-02-01 22:43:13,602 - Updated weight for [6 : Pratyush] to 115
INFO 2018-02-01 22:43:18,865 - Calculating weight for id None
INFO 2018-02-01 22:43:18,875 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:46:19,009 - Calculating weight for id None
INFO 2018-02-01 22:46:19,013 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-01 22:46:23,151 - Calculating weight for id None
INFO 2018-02-01 22:46:23,158 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:47:00,322 - Calculating weight for id None
INFO 2018-02-01 22:47:00,331 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:47:41,132 - Calculating weight for id None
INFO 2018-02-01 22:47:41,137 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:47:42,775 - Calculating weight for id None
INFO 2018-02-01 22:47:42,785 - Updated weight for [4 : Mahesh Waikar] to 82
INFO 2018-02-01 22:48:27,696 - Calculating weight for id None
INFO 2018-02-01 22:48:27,703 - Updated weight for [4 : Mahesh Waikar] to 82
INFO 2018-02-01 22:48:34,316 - Calculating weight for id None
INFO 2018-02-01 22:48:34,328 - Updated weight for [4 : Mahesh Waikar] to 49
INFO 2018-02-01 22:49:17,236 - Calculating weight for id None
INFO 2018-02-01 22:49:17,240 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-01 22:49:20,812 - Calculating weight for id None
INFO 2018-02-01 22:49:20,822 - Updated weight for [1 : Kalpesh Tawde] to 112
INFO 2018-02-01 22:49:24,612 - Calculating weight for id None
INFO 2018-02-01 22:49:24,618 - Updated weight for [1 : Kalpesh Tawde] to 112
INFO 2018-02-01 22:49:26,612 - Calculating weight for id None
INFO 2018-02-01 22:49:26,627 - Updated weight for [1 : Kalpesh Tawde] to 124
INFO 2018-02-01 22:49:28,311 - Calculating weight for id None
INFO 2018-02-01 22:49:28,322 - Updated weight for [1 : Kalpesh Tawde] to 136
INFO 2018-02-01 22:49:34,644 - Calculating weight for id None
INFO 2018-02-01 22:49:34,648 - Updated weight for [1 : Kalpesh Tawde] to 136
INFO 2018-02-01 22:49:36,059 - Calculating weight for id None
INFO 2018-02-01 22:49:36,068 - Updated weight for [1 : Kalpesh Tawde] to 148
INFO 2018-02-01 22:49:37,825 - Calculating weight for id None
INFO 2018-02-01 22:49:37,836 - Updated weight for [1 : Kalpesh Tawde] to 160
INFO 2018-02-01 22:49:38,079 - Calculating weight for id None
INFO 2018-02-01 22:49:38,089 - Updated weight for [1 : Kalpesh Tawde] to 172
INFO 2018-02-01 22:49:38,486 - Calculating weight for id None
INFO 2018-02-01 22:49:38,493 - Updated weight for [1 : Kalpesh Tawde] to 184
INFO 2018-02-01 22:49:41,497 - Calculating weight for id None
INFO 2018-02-01 22:49:41,502 - Updated weight for [1 : Kalpesh Tawde] to 184
INFO 2018-02-01 22:50:11,078 - Calculating weight for id None
INFO 2018-02-01 22:50:11,088 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-01 22:50:12,473 - Calculating weight for id None
INFO 2018-02-01 22:50:12,479 - Updated weight for [1 : Kalpesh Tawde] to 112
INFO 2018-02-01 22:50:14,151 - Calculating weight for id None
INFO 2018-02-01 22:50:14,155 - Updated weight for [1 : Kalpesh Tawde] to 112
INFO 2018-02-01 22:50:14,671 - Calculating weight for id None
INFO 2018-02-01 22:50:14,674 - Updated weight for [1 : Kalpesh Tawde] to 112
INFO 2018-02-01 22:50:14,989 - Calculating weight for id None
INFO 2018-02-01 22:50:14,993 - Updated weight for [1 : Kalpesh Tawde] to 112
INFO 2018-02-01 22:50:15,302 - Calculating weight for id None
INFO 2018-02-01 22:50:15,306 - Updated weight for [1 : Kalpesh Tawde] to 112
INFO 2018-02-01 22:50:16,602 - Calculating weight for id None
INFO 2018-02-01 22:50:16,607 - Updated weight for [1 : Kalpesh Tawde] to 112
INFO 2018-02-01 22:50:19,923 - Calculating weight for id None
INFO 2018-02-01 22:50:19,927 - Updated weight for [2 : Sagar Jagtap] to 100
INFO 2018-02-01 22:50:23,562 - Calculating weight for id None
INFO 2018-02-01 22:50:23,581 - Updated weight for [2 : Sagar Jagtap] to 107
INFO 2018-02-01 22:50:26,437 - Calculating weight for id None
INFO 2018-02-01 22:50:26,446 - Updated weight for [2 : Sagar Jagtap] to 100
INFO 2018-02-01 22:51:15,311 - Calculating weight for id None
INFO 2018-02-01 22:51:15,322 - Updated weight for [2 : Sagar Jagtap] to 100
INFO 2018-02-01 22:51:18,380 - Calculating weight for id None
INFO 2018-02-01 22:51:18,395 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:51:21,167 - Calculating weight for id None
INFO 2018-02-01 22:51:21,177 - Updated weight for [4 : Mahesh Waikar] to 57
INFO 2018-02-01 22:51:24,667 - Calculating weight for id None
INFO 2018-02-01 22:51:24,676 - Updated weight for [4 : Mahesh Waikar] to 67
INFO 2018-02-01 22:51:27,736 - Calculating weight for id None
INFO 2018-02-01 22:51:27,753 - Updated weight for [4 : Mahesh Waikar] to 67
INFO 2018-02-01 22:51:29,483 - Calculating weight for id None
INFO 2018-02-01 22:51:29,486 - Updated weight for [4 : Mahesh Waikar] to 67
INFO 2018-02-01 22:51:30,141 - Calculating weight for id None
INFO 2018-02-01 22:51:30,144 - Updated weight for [4 : Mahesh Waikar] to 67
INFO 2018-02-01 22:51:30,490 - Calculating weight for id None
INFO 2018-02-01 22:51:30,496 - Updated weight for [4 : Mahesh Waikar] to 67
INFO 2018-02-01 22:51:32,993 - Calculating weight for id None
INFO 2018-02-01 22:51:33,003 - Updated weight for [4 : Mahesh Waikar] to 97
INFO 2018-02-01 22:51:34,670 - Calculating weight for id None
INFO 2018-02-01 22:51:34,674 - Updated weight for [4 : Mahesh Waikar] to 97
INFO 2018-02-01 22:51:37,095 - Calculating weight for id None
INFO 2018-02-01 22:51:37,098 - Updated weight for [4 : Mahesh Waikar] to 67
INFO 2018-02-01 22:51:38,398 - Calculating weight for id None
INFO 2018-02-01 22:51:38,401 - Updated weight for [4 : Mahesh Waikar] to 67
INFO 2018-02-01 22:51:44,311 - Calculating weight for id None
INFO 2018-02-01 22:51:44,319 - Updated weight for [4 : Mahesh Waikar] to 67
INFO 2018-02-01 22:51:46,421 - Calculating weight for id None
INFO 2018-02-01 22:51:46,426 - Updated weight for [4 : Mahesh Waikar] to 97
INFO 2018-02-01 22:51:46,581 - Calculating weight for id None
INFO 2018-02-01 22:51:46,585 - Updated weight for [4 : Mahesh Waikar] to 97
INFO 2018-02-01 22:51:49,170 - Calculating weight for id None
INFO 2018-02-01 22:51:49,180 - Updated weight for [4 : Mahesh Waikar] to 127
INFO 2018-02-01 22:51:49,322 - Calculating weight for id None
INFO 2018-02-01 22:51:49,331 - Updated weight for [4 : Mahesh Waikar] to 127
INFO 2018-02-01 22:51:51,519 - Calculating weight for id None
INFO 2018-02-01 22:51:51,536 - Updated weight for [4 : Mahesh Waikar] to 130
INFO 2018-02-01 22:51:52,219 - Calculating weight for id None
INFO 2018-02-01 22:51:52,223 - Updated weight for [4 : Mahesh Waikar] to 130
INFO 2018-02-01 22:51:59,161 - Calculating weight for id None
INFO 2018-02-01 22:51:59,174 - Updated weight for [4 : Mahesh Waikar] to 120
INFO 2018-02-01 22:52:00,857 - Calculating weight for id None
INFO 2018-02-01 22:52:00,862 - Updated weight for [4 : Mahesh Waikar] to 120
INFO 2018-02-01 22:52:50,851 - Calculating weight for id None
INFO 2018-02-01 22:52:50,854 - Updated weight for [3 : Shruti Agarawal] to 100
ERROR 2018-02-01 22:52:50,855 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 25, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id, submit)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 96, in calc_weight_switch
    return self.newweight, self._data[id]["name"], dict(self._data[id]["mapping"])
AttributeError: 'recprec' object has no attribute 'newweight'
INFO 2018-02-01 22:53:44,427 - Calculating weight for id None
INFO 2018-02-01 22:53:44,431 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 22:53:47,576 - Calculating weight for id None
ERROR 2018-02-01 22:53:47,576 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 25, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id, submit)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 87, in calc_weight_switch
    new_weight += int(weight)
TypeError: cannot concatenate 'str' and 'int' objects
INFO 2018-02-01 22:53:59,595 - Calculating weight for id None
INFO 2018-02-01 22:53:59,885 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 22:54:02,255 - Calculating weight for id None
INFO 2018-02-01 22:54:02,269 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 22:54:04,397 - Calculating weight for id None
INFO 2018-02-01 22:54:04,405 - Updated weight for [3 : Shruti Agarawal] to 100
INFO 2018-02-01 22:54:08,438 - Calculating weight for id None
INFO 2018-02-01 22:54:08,448 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:55:02,344 - Calculating weight for id None
INFO 2018-02-01 22:55:02,348 - Updated weight for [5 : Gaurav Gupta] to 100
INFO 2018-02-01 22:55:05,105 - Calculating weight for id None
ERROR 2018-02-01 22:55:05,105 - Internal Server Error: /dashboard.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ktawde\hackathon\autobots\predire\views.py", line 25, in dashboard
    calc_weight, id_name, id_mapping = obj.calc_weight_switch(dict, id, submit)
  File "C:\Users\ktawde\hackathon\autobots\predire\static\scripts\recruit_predict.py", line 86, in calc_weight_switch
    new_weight += int(weight)
UnboundLocalError: local variable 'new_weight' referenced before assignment
INFO 2018-02-01 22:55:33,217 - Calculating weight for id None
INFO 2018-02-01 22:55:33,229 - Updated weight for [5 : Gaurav Gupta] to 82
INFO 2018-02-01 22:55:34,884 - Calculating weight for id None
INFO 2018-02-01 22:55:34,898 - Updated weight for [5 : Gaurav Gupta] to 82
INFO 2018-02-01 22:55:37,390 - Calculating weight for id None
INFO 2018-02-01 22:55:37,398 - Updated weight for [5 : Gaurav Gupta] to 72
INFO 2018-02-01 22:55:39,825 - Calculating weight for id None
INFO 2018-02-01 22:55:39,835 - Updated weight for [5 : Gaurav Gupta] to 57
INFO 2018-02-01 22:55:43,463 - Calculating weight for id None
INFO 2018-02-01 22:55:43,469 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-01 22:55:46,177 - Calculating weight for id None
INFO 2018-02-01 22:55:46,186 - Updated weight for [5 : Gaurav Gupta] to 100
INFO 2018-02-01 22:57:29,048 - Calculating weight for id None
INFO 2018-02-01 22:57:29,053 - Updated weight for [5 : Gaurav Gupta] to 100
INFO 2018-02-01 22:58:44,411 - Calculating weight for id None
INFO 2018-02-01 22:58:46,049 - Calculating weight for id None
INFO 2018-02-01 22:58:46,055 - Updated weight for [5 : Gaurav Gupta] to 57
INFO 2018-02-01 22:58:49,808 - Calculating weight for id None
INFO 2018-02-01 22:58:51,730 - Calculating weight for id None
INFO 2018-02-01 22:58:51,734 - Updated weight for [5 : Gaurav Gupta] to 57
INFO 2018-02-01 22:58:54,885 - Calculating weight for id None
INFO 2018-02-01 22:58:56,880 - Calculating weight for id None
INFO 2018-02-01 22:58:59,184 - Calculating weight for id None
INFO 2018-02-01 22:58:59,191 - Updated weight for [4 : Mahesh Waikar] to 117
INFO 2018-02-01 22:59:02,710 - Calculating weight for id None
INFO 2018-02-01 22:59:06,447 - Calculating weight for id None
INFO 2018-02-01 22:59:07,457 - Calculating weight for id None
INFO 2018-02-01 22:59:07,463 - Updated weight for [4 : Mahesh Waikar] to 117
INFO 2018-02-01 22:59:07,630 - Calculating weight for id None
INFO 2018-02-01 22:59:07,634 - Updated weight for [4 : Mahesh Waikar] to 117
INFO 2018-02-01 22:59:07,908 - Calculating weight for id None
INFO 2018-02-01 22:59:07,914 - Updated weight for [4 : Mahesh Waikar] to 117
INFO 2018-02-01 23:06:09,035 - Calculating weight for id None
INFO 2018-02-01 23:06:09,039 - Updated weight for [4 : Mahesh Waikar] to 117
INFO 2018-02-01 23:06:13,427 - Calculating weight for id None
INFO 2018-02-01 23:06:13,431 - Updated weight for [4 : Mahesh Waikar] to 117
INFO 2018-02-01 23:06:15,937 - Calculating weight for id None
INFO 2018-02-01 23:06:15,941 - Updated weight for [4 : Mahesh Waikar] to 117
INFO 2018-02-01 23:06:18,828 - Calculating weight for id None
INFO 2018-02-01 23:06:18,832 - Updated weight for [4 : Mahesh Waikar] to 117
INFO 2018-02-01 23:06:19,940 - Calculating weight for id None
INFO 2018-02-01 23:06:19,946 - Updated weight for [4 : Mahesh Waikar] to 117
INFO 2018-02-01 23:06:24,822 - Calculating weight for id None
INFO 2018-02-01 23:06:27,223 - Calculating weight for id None
INFO 2018-02-01 23:06:27,233 - Updated weight for [4 : Mahesh Waikar] to 127
INFO 2018-02-01 23:06:40,098 - Calculating weight for id None
INFO 2018-02-01 23:06:42,967 - Calculating weight for id None
INFO 2018-02-01 23:10:39,394 - Calculating weight for id None
INFO 2018-02-01 23:10:42,786 - Calculating weight for id None
INFO 2018-02-01 23:10:42,806 - Updated weight for [5 : Gaurav Gupta] to 57
INFO 2018-02-01 23:12:07,230 - Calculating weight for id None
INFO 2018-02-01 23:12:07,236 - Updated weight for [5 : Gaurav Gupta] to 57
INFO 2018-02-01 23:12:11,474 - Calculating weight for id None
INFO 2018-02-01 23:12:11,480 - Updated weight for [5 : Gaurav Gupta] to 57
INFO 2018-02-01 23:12:12,967 - Calculating weight for id None
INFO 2018-02-01 23:12:12,970 - Updated weight for [5 : Gaurav Gupta] to 57
WARNING 2018-02-02 09:33:11,747 - Not Found: /favicon.ico
INFO 2018-02-02 09:33:13,855 - Calculating weight for id None
INFO 2018-02-02 09:33:17,224 - Calculating weight for id None
INFO 2018-02-02 09:33:17,233 - Updated weight for [6 : Pratyush] to 112
INFO 2018-02-02 09:33:20,036 - Calculating weight for id None
INFO 2018-02-02 09:33:20,046 - Updated weight for [6 : Pratyush] to 97
INFO 2018-02-02 09:33:25,352 - Calculating weight for id None
INFO 2018-02-02 09:42:48,664 - Calculating weight for id None
INFO 2018-02-02 09:42:48,674 - Updated weight for [6 : Pratyush] to 57
INFO 2018-02-02 09:42:53,730 - Calculating weight for id None
INFO 2018-02-02 09:42:55,760 - Calculating weight for id None
INFO 2018-02-02 09:42:55,773 - Updated weight for [3 : Shruti Agarawal] to 75
INFO 2018-02-02 09:42:58,187 - Calculating weight for id None
INFO 2018-02-02 09:42:58,194 - Updated weight for [3 : Shruti Agarawal] to 60
INFO 2018-02-02 09:43:04,861 - Calculating weight for id None
INFO 2018-02-02 09:43:04,880 - Updated weight for [3 : Shruti Agarawal] to 70
INFO 2018-02-02 09:43:12,042 - Calculating weight for id None
INFO 2018-02-02 09:43:14,140 - Calculating weight for id None
INFO 2018-02-02 09:43:14,148 - Updated weight for [4 : Mahesh Waikar] to 137
INFO 2018-02-02 09:43:15,921 - Calculating weight for id None
INFO 2018-02-02 09:43:15,931 - Updated weight for [4 : Mahesh Waikar] to 140
INFO 2018-02-02 09:43:17,934 - Calculating weight for id None
INFO 2018-02-02 09:43:17,941 - Updated weight for [4 : Mahesh Waikar] to 155
INFO 2018-02-02 09:47:12,005 - Calculating weight for id None
INFO 2018-02-02 09:47:14,993 - Calculating weight for id None
INFO 2018-02-02 09:47:15,002 - Updated weight for [4 : Mahesh Waikar] to 85
INFO 2018-02-02 09:47:18,680 - Calculating weight for id None
INFO 2018-02-02 09:47:18,694 - Updated weight for [4 : Mahesh Waikar] to 115
INFO 2018-02-02 09:47:26,637 - Calculating weight for id None
INFO 2018-02-02 09:47:26,644 - Updated weight for [4 : Mahesh Waikar] to 85
INFO 2018-02-02 09:47:29,176 - Calculating weight for id None
INFO 2018-02-02 09:47:29,184 - Updated weight for [4 : Mahesh Waikar] to 70
INFO 2018-02-02 09:48:18,799 - Calculating weight for id None
INFO 2018-02-02 09:48:18,805 - Updated weight for [4 : Mahesh Waikar] to 70
INFO 2018-02-02 09:48:22,283 - Calculating weight for id None
INFO 2018-02-02 09:48:22,289 - Updated weight for [4 : Mahesh Waikar] to 85
INFO 2018-02-02 09:48:24,285 - Calculating weight for id None
INFO 2018-02-02 09:48:24,290 - Updated weight for [4 : Mahesh Waikar] to 70
INFO 2018-02-02 09:48:29,000 - Calculating weight for id None
INFO 2018-02-02 09:48:29,015 - Updated weight for [4 : Mahesh Waikar] to 67
INFO 2018-02-02 09:48:32,872 - Calculating weight for id None
INFO 2018-02-02 09:48:32,881 - Updated weight for [4 : Mahesh Waikar] to 57
INFO 2018-02-02 09:48:35,464 - Calculating weight for id None
INFO 2018-02-02 09:48:35,473 - Updated weight for [4 : Mahesh Waikar] to 87
INFO 2018-02-02 09:48:40,358 - Calculating weight for id None
INFO 2018-02-02 09:48:40,365 - Updated weight for [4 : Mahesh Waikar] to 97
INFO 2018-02-02 09:49:55,627 - Calculating weight for id None
INFO 2018-02-02 09:49:55,631 - Updated weight for [4 : Mahesh Waikar] to 97
INFO 2018-02-02 09:49:59,576 - Calculating weight for id None
INFO 2018-02-02 09:49:59,581 - Updated weight for [4 : Mahesh Waikar] to 87
INFO 2018-02-02 09:50:01,545 - Calculating weight for id None
INFO 2018-02-02 09:50:01,549 - Updated weight for [4 : Mahesh Waikar] to 97
INFO 2018-02-02 09:50:04,141 - Calculating weight for id None
INFO 2018-02-02 09:50:04,150 - Updated weight for [4 : Mahesh Waikar] to 127
INFO 2018-02-02 09:50:08,848 - Calculating weight for id None
INFO 2018-02-02 09:50:08,858 - Updated weight for [4 : Mahesh Waikar] to 142
INFO 2018-02-02 09:50:10,176 - Calculating weight for id None
INFO 2018-02-02 09:50:10,178 - Updated weight for [4 : Mahesh Waikar] to 142
INFO 2018-02-02 09:50:11,865 - Calculating weight for id None
INFO 2018-02-02 09:50:11,874 - Updated weight for [4 : Mahesh Waikar] to 145
INFO 2018-02-02 09:50:17,319 - Calculating weight for id None
INFO 2018-02-02 09:50:17,325 - Updated weight for [4 : Mahesh Waikar] to 115
INFO 2018-02-02 09:50:19,640 - Calculating weight for id None
INFO 2018-02-02 09:50:19,655 - Updated weight for [4 : Mahesh Waikar] to 125
INFO 2018-02-02 09:50:32,503 - Calculating weight for id None
INFO 2018-02-02 09:50:32,509 - Updated weight for [4 : Mahesh Waikar] to 125
INFO 2018-02-02 09:50:36,273 - Calculating weight for id None
INFO 2018-02-02 09:50:36,280 - Updated weight for [4 : Mahesh Waikar] to 122
INFO 2018-02-02 09:50:47,914 - Calculating weight for id None
INFO 2018-02-02 09:50:47,924 - Updated weight for [4 : Mahesh Waikar] to 152
INFO 2018-02-02 09:50:59,914 - Calculating weight for id None
INFO 2018-02-02 09:50:59,930 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-02 09:51:01,348 - Calculating weight for id None
INFO 2018-02-02 09:51:01,352 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-02 09:51:08,135 - Calculating weight for id None
INFO 2018-02-02 09:51:08,140 - Updated weight for [4 : Mahesh Waikar] to 85
INFO 2018-02-02 09:51:12,378 - Calculating weight for id None
INFO 2018-02-02 09:51:12,387 - Updated weight for [4 : Mahesh Waikar] to 115
INFO 2018-02-02 09:51:15,019 - Calculating weight for id None
INFO 2018-02-02 09:51:15,023 - Updated weight for [4 : Mahesh Waikar] to 85
INFO 2018-02-02 09:51:16,854 - Calculating weight for id None
INFO 2018-02-02 09:51:16,864 - Updated weight for [4 : Mahesh Waikar] to 82
INFO 2018-02-02 09:51:19,039 - Calculating weight for id None
INFO 2018-02-02 09:51:19,046 - Updated weight for [4 : Mahesh Waikar] to 72
INFO 2018-02-02 09:51:21,227 - Calculating weight for id None
INFO 2018-02-02 09:51:21,236 - Updated weight for [4 : Mahesh Waikar] to 57
INFO 2018-02-02 09:51:24,186 - Calculating weight for id None
INFO 2018-02-02 09:51:24,196 - Updated weight for [4 : Mahesh Waikar] to 87
INFO 2018-02-02 09:51:26,709 - Calculating weight for id None
INFO 2018-02-02 09:51:26,713 - Updated weight for [4 : Mahesh Waikar] to 57
INFO 2018-02-02 09:51:32,362 - Calculating weight for id None
INFO 2018-02-02 09:51:32,375 - Updated weight for [4 : Mahesh Waikar] to 72
INFO 2018-02-02 09:51:37,256 - Calculating weight for id None
INFO 2018-02-02 09:51:37,267 - Updated weight for [4 : Mahesh Waikar] to 75
INFO 2018-02-02 09:51:47,322 - Calculating weight for id None
INFO 2018-02-02 09:51:47,328 - Updated weight for [4 : Mahesh Waikar] to 75
INFO 2018-02-02 09:54:54,471 - Calculating weight for id None
INFO 2018-02-02 09:54:54,476 - Updated weight for [4 : Mahesh Waikar] to 75
INFO 2018-02-02 09:55:36,780 - Calculating weight for id None
INFO 2018-02-02 09:55:36,882 - Updated weight for [4 : Mahesh Waikar] to 75
INFO 2018-02-02 09:55:40,177 - Calculating weight for id None
INFO 2018-02-02 09:55:40,180 - Updated weight for [4 : Mahesh Waikar] to 75
INFO 2018-02-02 09:56:34,971 - Calculating weight for id None
INFO 2018-02-02 09:56:35,415 - Updated weight for [4 : Mahesh Waikar] to 75
INFO 2018-02-02 09:56:40,701 - Calculating weight for id None
INFO 2018-02-02 09:56:40,711 - Updated weight for [4 : Mahesh Waikar] to 105
INFO 2018-02-02 09:59:46,974 - Calculating weight for id None
INFO 2018-02-02 09:59:46,984 - Updated weight for [4 : Mahesh Waikar] to 120
INFO 2018-02-02 09:59:51,855 - Calculating weight for id None
INFO 2018-02-02 09:59:51,869 - Updated weight for [4 : Mahesh Waikar] to 105
INFO 2018-02-02 09:59:53,308 - Calculating weight for id None
INFO 2018-02-02 09:59:53,312 - Updated weight for [4 : Mahesh Waikar] to 105
INFO 2018-02-02 09:59:55,009 - Calculating weight for id None
INFO 2018-02-02 09:59:55,019 - Updated weight for [4 : Mahesh Waikar] to 102
INFO 2018-02-02 09:59:59,697 - Calculating weight for id None
INFO 2018-02-02 10:00:03,275 - Calculating weight for id None
INFO 2018-02-02 10:00:03,282 - Updated weight for [3 : Shruti Agarawal] to 130
INFO 2018-02-02 10:00:05,937 - Calculating weight for id None
INFO 2018-02-02 10:00:05,944 - Updated weight for [3 : Shruti Agarawal] to 127
INFO 2018-02-02 10:00:06,865 - Calculating weight for id None
INFO 2018-02-02 10:00:06,871 - Updated weight for [3 : Shruti Agarawal] to 127
INFO 2018-02-02 10:00:07,677 - Calculating weight for id None
INFO 2018-02-02 10:00:07,680 - Updated weight for [3 : Shruti Agarawal] to 127
INFO 2018-02-02 10:00:08,463 - Calculating weight for id None
INFO 2018-02-02 10:00:08,473 - Updated weight for [3 : Shruti Agarawal] to 127
INFO 2018-02-02 10:00:08,677 - Calculating weight for id None
INFO 2018-02-02 10:00:08,681 - Updated weight for [3 : Shruti Agarawal] to 127
INFO 2018-02-02 10:00:08,993 - Calculating weight for id None
INFO 2018-02-02 10:00:08,997 - Updated weight for [3 : Shruti Agarawal] to 127
INFO 2018-02-02 10:00:09,355 - Calculating weight for id None
INFO 2018-02-02 10:00:09,358 - Updated weight for [3 : Shruti Agarawal] to 127
INFO 2018-02-02 10:01:05,188 - Calculating weight for id None
INFO 2018-02-02 10:01:05,207 - Updated weight for [3 : Shruti Agarawal] to 127
INFO 2018-02-02 10:01:14,207 - Calculating weight for id None
INFO 2018-02-02 10:01:21,611 - Calculating weight for id None
INFO 2018-02-02 10:01:21,621 - Updated weight for [6 : Pratyush] to 85
INFO 2018-02-02 10:01:25,022 - Calculating weight for id None
INFO 2018-02-02 10:01:25,045 - Updated weight for [6 : Pratyush] to 115
INFO 2018-02-02 10:01:31,900 - Calculating weight for id None
INFO 2018-02-02 10:01:31,903 - Updated weight for [6 : Pratyush] to 85
INFO 2018-02-02 10:01:36,361 - Calculating weight for id None
INFO 2018-02-02 10:01:36,365 - Updated weight for [6 : Pratyush] to 115
INFO 2018-02-02 10:01:39,476 - Calculating weight for id None
INFO 2018-02-02 10:01:39,490 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-02 10:01:54,917 - Calculating weight for id None
INFO 2018-02-02 10:01:54,921 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-02 10:01:57,786 - Calculating weight for id None
INFO 2018-02-02 10:01:57,792 - Updated weight for [6 : Pratyush] to 100
INFO 2018-02-02 10:02:01,352 - Calculating weight for id None
INFO 2018-02-02 10:02:03,681 - Calculating weight for id None
INFO 2018-02-02 10:02:03,687 - Updated weight for [6 : Pratyush] to 115
INFO 2018-02-02 10:02:06,003 - Calculating weight for id None
INFO 2018-02-02 10:02:06,013 - Updated weight for [6 : Pratyush] to 112
INFO 2018-02-02 10:02:08,163 - Calculating weight for id None
INFO 2018-02-02 10:02:08,186 - Updated weight for [6 : Pratyush] to 82
INFO 2018-02-02 10:02:51,733 - Calculating weight for id None
INFO 2018-02-02 10:02:51,736 - Updated weight for [6 : Pratyush] to 82
INFO 2018-02-02 10:02:54,043 - Calculating weight for id None
INFO 2018-02-02 10:02:54,048 - Updated weight for [6 : Pratyush] to 112
INFO 2018-02-02 10:02:58,019 - Calculating weight for id None
INFO 2018-02-02 10:02:58,029 - Updated weight for [6 : Pratyush] to 97
INFO 2018-02-02 10:03:01,171 - Calculating weight for id None
INFO 2018-02-02 10:03:01,180 - Updated weight for [6 : Pratyush] to 87
INFO 2018-02-02 10:03:03,384 - Calculating weight for id None
INFO 2018-02-02 10:03:03,392 - Updated weight for [6 : Pratyush] to 97
INFO 2018-02-02 10:03:05,474 - Calculating weight for id None
INFO 2018-02-02 10:03:05,484 - Updated weight for [6 : Pratyush] to 67
INFO 2018-02-02 10:03:20,308 - Calculating weight for id None
INFO 2018-02-02 10:03:20,318 - Updated weight for [6 : Pratyush] to 85
INFO 2018-02-02 10:03:24,585 - Calculating weight for id None
INFO 2018-02-02 10:03:28,440 - Calculating weight for id None
INFO 2018-02-02 10:03:28,446 - Updated weight for [6 : Pratyush] to 115
INFO 2018-02-02 10:05:57,658 - Calculating weight for id None
INFO 2018-02-02 10:06:02,280 - Calculating weight for id None
INFO 2018-02-02 10:06:02,292 - Updated weight for [4 : Mahesh Waikar] to 85
INFO 2018-02-02 10:06:07,289 - Calculating weight for id None
INFO 2018-02-02 10:06:07,296 - Updated weight for [4 : Mahesh Waikar] to 80
INFO 2018-02-02 10:06:26,002 - Calculating weight for id None
INFO 2018-02-02 10:06:26,006 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-02 10:06:37,871 - Calculating weight for id None
INFO 2018-02-02 10:06:37,882 - Updated weight for [4 : Mahesh Waikar] to 85
INFO 2018-02-02 10:06:40,134 - Calculating weight for id None
INFO 2018-02-02 10:06:40,144 - Updated weight for [4 : Mahesh Waikar] to 82
INFO 2018-02-02 10:06:42,161 - Calculating weight for id None
INFO 2018-02-02 10:06:42,167 - Updated weight for [4 : Mahesh Waikar] to 77
INFO 2018-02-02 10:06:44,979 - Calculating weight for id None
INFO 2018-02-02 10:06:44,990 - Updated weight for [4 : Mahesh Waikar] to 47
INFO 2018-02-02 10:07:00,687 - Calculating weight for id None
INFO 2018-02-02 10:07:00,694 - Updated weight for [4 : Mahesh Waikar] to 72
INFO 2018-02-02 10:07:03,519 - Calculating weight for id None
INFO 2018-02-02 10:07:03,523 - Updated weight for [4 : Mahesh Waikar] to 77
INFO 2018-02-02 10:07:06,298 - Calculating weight for id None
INFO 2018-02-02 10:07:06,302 - Updated weight for [4 : Mahesh Waikar] to 72
INFO 2018-02-02 10:07:07,828 - Calculating weight for id None
INFO 2018-02-02 10:07:07,835 - Updated weight for [4 : Mahesh Waikar] to 77
INFO 2018-02-02 10:07:09,325 - Calculating weight for id None
INFO 2018-02-02 10:07:09,329 - Updated weight for [4 : Mahesh Waikar] to 72
INFO 2018-02-02 10:07:12,253 - Calculating weight for id None
INFO 2018-02-02 10:07:12,260 - Updated weight for [4 : Mahesh Waikar] to 57
INFO 2018-02-02 10:07:14,960 - Calculating weight for id None
INFO 2018-02-02 10:07:14,969 - Updated weight for [4 : Mahesh Waikar] to 52
INFO 2018-02-02 10:07:25,559 - Calculating weight for id None
INFO 2018-02-02 10:07:25,569 - Updated weight for [4 : Mahesh Waikar] to 22
INFO 2018-02-02 10:07:28,444 - Calculating weight for id None
INFO 2018-02-02 10:07:28,459 - Updated weight for [4 : Mahesh Waikar] to 52
INFO 2018-02-02 10:07:56,250 - Calculating weight for id None
INFO 2018-02-02 10:07:56,255 - Updated weight for [4 : Mahesh Waikar] to 57
INFO 2018-02-02 10:08:22,726 - Calculating weight for id None
INFO 2018-02-02 10:08:22,733 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-02 10:09:10,726 - Calculating weight for id None
INFO 2018-02-02 10:09:10,736 - Updated weight for [4 : Mahesh Waikar] to 100
INFO 2018-02-02 10:09:13,736 - Calculating weight for id None
INFO 2018-02-02 10:09:33,808 - Calculating weight for id None
INFO 2018-02-02 10:09:38,730 - Calculating weight for id None
INFO 2018-02-02 10:09:38,736 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-02 10:09:42,776 - Calculating weight for id None
INFO 2018-02-02 10:09:42,789 - Updated weight for [1 : Kalpesh Tawde] to 95
INFO 2018-02-02 10:09:49,289 - Calculating weight for id None
INFO 2018-02-02 10:09:49,293 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-02 10:10:14,852 - Calculating weight for id None
INFO 2018-02-02 10:10:14,859 - Updated weight for [1 : Kalpesh Tawde] to 105
INFO 2018-02-02 10:10:17,790 - Calculating weight for id None
INFO 2018-02-02 10:10:17,793 - Updated weight for [1 : Kalpesh Tawde] to 105
INFO 2018-02-02 10:10:20,457 - Calculating weight for id None
INFO 2018-02-02 10:10:20,461 - Updated weight for [1 : Kalpesh Tawde] to 105
INFO 2018-02-02 10:10:22,677 - Calculating weight for id None
INFO 2018-02-02 10:10:22,690 - Updated weight for [1 : Kalpesh Tawde] to 90
INFO 2018-02-02 10:10:49,184 - Calculating weight for id None
INFO 2018-02-02 10:10:49,188 - Updated weight for [1 : Kalpesh Tawde] to 90
INFO 2018-02-02 10:10:51,542 - Calculating weight for id None
INFO 2018-02-02 10:10:51,555 - Updated weight for [1 : Kalpesh Tawde] to 105
INFO 2018-02-02 10:11:00,207 - Calculating weight for id None
INFO 2018-02-02 10:11:00,223 - Updated weight for [1 : Kalpesh Tawde] to 85
INFO 2018-02-02 10:11:04,355 - Calculating weight for id None
INFO 2018-02-02 10:11:04,359 - Updated weight for [1 : Kalpesh Tawde] to 85
INFO 2018-02-02 10:11:10,822 - Calculating weight for id None
INFO 2018-02-02 10:11:10,828 - Updated weight for [1 : Kalpesh Tawde] to 85
INFO 2018-02-02 10:11:17,676 - Calculating weight for id None
INFO 2018-02-02 10:11:17,683 - Updated weight for [1 : Kalpesh Tawde] to 85
INFO 2018-02-02 10:11:20,348 - Calculating weight for id None
INFO 2018-02-02 10:11:20,355 - Updated weight for [1 : Kalpesh Tawde] to 82
INFO 2018-02-02 10:11:22,548 - Calculating weight for id None
INFO 2018-02-02 10:11:22,555 - Updated weight for [1 : Kalpesh Tawde] to 77
INFO 2018-02-02 10:11:26,006 - Calculating weight for id None
INFO 2018-02-02 10:11:26,019 - Updated weight for [1 : Kalpesh Tawde] to 82
INFO 2018-02-02 10:16:18,020 - Calculating weight for id None
INFO 2018-02-02 10:16:20,377 - Calculating weight for id None
INFO 2018-02-02 10:16:29,585 - Calculating weight for id None
INFO 2018-02-02 10:16:29,598 - Updated weight for [1 : Kalpesh Tawde] to 85
INFO 2018-02-02 10:17:26,963 - Calculating weight for id None
INFO 2018-02-02 10:17:30,227 - Calculating weight for id None
INFO 2018-02-02 10:17:30,233 - Updated weight for [1 : Kalpesh Tawde] to 85
INFO 2018-02-02 10:17:57,779 - Calculating weight for id None
INFO 2018-02-02 10:17:57,786 - Updated weight for [1 : Kalpesh Tawde] to 95
INFO 2018-02-02 10:18:01,115 - Calculating weight for id None
INFO 2018-02-02 10:18:01,130 - Updated weight for [1 : Kalpesh Tawde] to 80
INFO 2018-02-02 10:18:03,565 - Calculating weight for id None
INFO 2018-02-02 10:18:03,572 - Updated weight for [1 : Kalpesh Tawde] to 85
INFO 2018-02-02 10:18:05,756 - Calculating weight for id None
INFO 2018-02-02 10:18:05,763 - Updated weight for [1 : Kalpesh Tawde] to 90
INFO 2018-02-02 10:18:07,865 - Calculating weight for id None
INFO 2018-02-02 10:18:07,878 - Updated weight for [1 : Kalpesh Tawde] to 60
INFO 2018-02-02 10:18:10,480 - Calculating weight for id None
INFO 2018-02-02 10:18:10,490 - Updated weight for [1 : Kalpesh Tawde] to 65
INFO 2018-02-02 10:18:13,585 - Calculating weight for id None
INFO 2018-02-02 10:18:13,596 - Updated weight for [1 : Kalpesh Tawde] to 80
INFO 2018-02-02 10:18:22,224 - Calculating weight for id None
INFO 2018-02-02 10:18:22,230 - Updated weight for [1 : Kalpesh Tawde] to 65
INFO 2018-02-02 10:18:30,446 - Calculating weight for id None
INFO 2018-02-02 10:18:30,450 - Updated weight for [1 : Kalpesh Tawde] to 80
INFO 2018-02-02 10:18:55,640 - Calculating weight for id None
INFO 2018-02-02 10:18:55,644 - Updated weight for [1 : Kalpesh Tawde] to 65
INFO 2018-02-02 10:19:31,023 - Calculating weight for id None
INFO 2018-02-02 10:19:31,028 - Updated weight for [1 : Kalpesh Tawde] to 65
INFO 2018-02-02 10:19:32,861 - Calculating weight for id None
INFO 2018-02-02 10:19:32,868 - Updated weight for [1 : Kalpesh Tawde] to 65
INFO 2018-02-02 10:19:34,756 - Calculating weight for id None
INFO 2018-02-02 10:19:34,767 - Updated weight for [1 : Kalpesh Tawde] to 60
INFO 2018-02-02 10:20:38,493 - Calculating weight for id None
INFO 2018-02-02 10:20:38,497 - Updated weight for [1 : Kalpesh Tawde] to 60
INFO 2018-02-02 10:20:41,223 - Calculating weight for id None
INFO 2018-02-02 10:20:41,226 - Updated weight for [1 : Kalpesh Tawde] to 60
INFO 2018-02-02 10:21:55,444 - Calculating weight for id None
INFO 2018-02-02 10:22:05,556 - Calculating weight for id None
INFO 2018-02-02 10:22:05,565 - Updated weight for [1 : Kalpesh Tawde] to 125
INFO 2018-02-02 10:22:28,415 - Calculating weight for id None
INFO 2018-02-02 10:22:28,427 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-02 10:22:31,680 - Calculating weight for id None
INFO 2018-02-02 10:22:31,688 - Updated weight for [1 : Kalpesh Tawde] to 105
INFO 2018-02-02 10:22:35,697 - Calculating weight for id None
INFO 2018-02-02 10:22:35,701 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-02 10:22:39,677 - Calculating weight for id None
INFO 2018-02-02 10:22:39,681 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-02 10:22:40,562 - Calculating weight for id None
INFO 2018-02-02 10:22:40,566 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-02 10:22:41,049 - Calculating weight for id None
INFO 2018-02-02 10:22:41,055 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-02 10:22:41,762 - Calculating weight for id None
INFO 2018-02-02 10:22:41,766 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-02 10:22:43,490 - Calculating weight for id None
INFO 2018-02-02 10:22:43,499 - Updated weight for [1 : Kalpesh Tawde] to 85
INFO 2018-02-02 10:22:49,237 - Calculating weight for id None
INFO 2018-02-02 10:22:49,259 - Updated weight for [1 : Kalpesh Tawde] to 90
INFO 2018-02-02 10:22:51,648 - Calculating weight for id None
INFO 2018-02-02 10:22:51,658 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-02 10:22:55,588 - Calculating weight for id None
INFO 2018-02-02 10:22:55,594 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-02 10:24:35,463 - Calculating weight for id None
INFO 2018-02-02 10:24:43,823 - Calculating weight for id None
INFO 2018-02-02 10:24:43,832 - Updated weight for [1 : Kalpesh Tawde] to 75
INFO 2018-02-02 10:24:52,875 - Calculating weight for id None
INFO 2018-02-02 10:24:52,878 - Updated weight for [1 : Kalpesh Tawde] to 75
INFO 2018-02-02 10:24:55,877 - Calculating weight for id None
INFO 2018-02-02 10:24:55,884 - Updated weight for [1 : Kalpesh Tawde] to 80
INFO 2018-02-02 10:24:59,490 - Calculating weight for id None
INFO 2018-02-02 10:24:59,499 - Updated weight for [1 : Kalpesh Tawde] to 75
INFO 2018-02-02 10:25:01,335 - Calculating weight for id None
INFO 2018-02-02 10:25:01,338 - Updated weight for [1 : Kalpesh Tawde] to 80
INFO 2018-02-02 10:25:04,061 - Calculating weight for id None
INFO 2018-02-02 10:25:04,069 - Updated weight for [1 : Kalpesh Tawde] to 90
INFO 2018-02-02 10:25:06,028 - Calculating weight for id None
INFO 2018-02-02 10:25:06,032 - Updated weight for [1 : Kalpesh Tawde] to 75
INFO 2018-02-02 10:25:48,516 - Calculating weight for id None
INFO 2018-02-02 10:25:51,825 - Calculating weight for id None
INFO 2018-02-02 10:25:51,835 - Updated weight for [1 : Kalpesh Tawde] to 105
INFO 2018-02-02 10:25:55,095 - Calculating weight for id None
INFO 2018-02-02 10:25:55,098 - Updated weight for [1 : Kalpesh Tawde] to 90
INFO 2018-02-02 10:25:58,773 - Calculating weight for id None
INFO 2018-02-02 10:25:58,778 - Updated weight for [1 : Kalpesh Tawde] to 105
INFO 2018-02-02 10:26:00,648 - Calculating weight for id None
INFO 2018-02-02 10:26:00,651 - Updated weight for [1 : Kalpesh Tawde] to 90
INFO 2018-02-02 10:26:06,723 - Calculating weight for id None
INFO 2018-02-02 10:26:06,727 - Updated weight for [1 : Kalpesh Tawde] to 90
INFO 2018-02-02 10:26:37,917 - Calculating weight for id None
INFO 2018-02-02 10:26:37,928 - Updated weight for [1 : Kalpesh Tawde] to 100
INFO 2018-02-02 10:26:41,740 - Calculating weight for id None
INFO 2018-02-02 10:26:41,743 - Updated weight for [1 : Kalpesh Tawde] to 85
INFO 2018-02-02 10:26:43,927 - Calculating weight for id None
INFO 2018-02-02 10:26:43,934 - Updated weight for [1 : Kalpesh Tawde] to 90
INFO 2018-02-02 10:26:47,459 - Calculating weight for id None
INFO 2018-02-02 10:26:47,467 - Updated weight for [1 : Kalpesh Tawde] to 70
INFO 2018-02-02 10:26:50,381 - Calculating weight for id None
INFO 2018-02-02 10:26:50,388 - Updated weight for [1 : Kalpesh Tawde] to 75
INFO 2018-02-02 10:26:55,799 - Calculating weight for id None
INFO 2018-02-02 10:26:55,809 - Updated weight for [1 : Kalpesh Tawde] to 90
INFO 2018-02-02 10:26:59,861 - Calculating weight for id None
INFO 2018-02-02 10:26:59,869 - Updated weight for [1 : Kalpesh Tawde] to 85
INFO 2018-02-02 10:28:12,253 - Calculating weight for id None
INFO 2018-02-02 10:28:21,576 - Calculating weight for id None
INFO 2018-02-02 10:28:24,112 - Calculating weight for id None
INFO 2018-02-02 10:28:24,121 - Updated weight for [4 : Mahesh Waikar] to 35
INFO 2018-02-02 10:28:31,989 - Calculating weight for id None
INFO 2018-02-02 10:28:31,996 - Updated weight for [4 : Mahesh Waikar] to 45
INFO 2018-02-02 10:28:35,851 - Calculating weight for id None
INFO 2018-02-02 10:28:35,861 - Updated weight for [4 : Mahesh Waikar] to 50
INFO 2018-02-02 10:28:38,586 - Calculating weight for id None
INFO 2018-02-02 10:28:38,596 - Updated weight for [4 : Mahesh Waikar] to 55
INFO 2018-02-02 10:29:04,459 - Calculating weight for id None
INFO 2018-02-02 10:29:04,464 - Updated weight for [4 : Mahesh Waikar] to 55
INFO 2018-02-02 10:29:09,634 - Calculating weight for id None
INFO 2018-02-02 10:29:09,647 - Updated weight for [4 : Mahesh Waikar] to 40
INFO 2018-02-02 10:29:12,519 - Calculating weight for id None
INFO 2018-02-02 10:29:12,528 - Updated weight for [4 : Mahesh Waikar] to 20
INFO 2018-02-02 10:29:41,499 - Calculating weight for id None
INFO 2018-02-02 10:29:41,505 - Updated weight for [4 : Mahesh Waikar] to 40
INFO 2018-02-02 10:29:43,549 - Calculating weight for id None
INFO 2018-02-02 10:29:43,563 - Updated weight for [4 : Mahesh Waikar] to 60
INFO 2018-02-02 10:29:45,930 - Calculating weight for id None
INFO 2018-02-02 10:29:45,938 - Updated weight for [4 : Mahesh Waikar] to 60
INFO 2018-02-02 10:29:46,536 - Calculating weight for id None
INFO 2018-02-02 10:29:46,546 - Updated weight for [4 : Mahesh Waikar] to 60
INFO 2018-02-02 10:29:47,081 - Calculating weight for id None
INFO 2018-02-02 10:29:47,085 - Updated weight for [4 : Mahesh Waikar] to 60
INFO 2018-02-02 10:30:06,234 - Calculating weight for id None
INFO 2018-02-02 10:30:06,243 - Updated weight for [4 : Mahesh Waikar] to 20
INFO 2018-02-02 10:30:08,582 - Calculating weight for id None
INFO 2018-02-02 10:30:08,592 - Updated weight for [4 : Mahesh Waikar] to 20
INFO 2018-02-02 10:30:10,459 - Calculating weight for id None
INFO 2018-02-02 10:30:10,463 - Updated weight for [4 : Mahesh Waikar] to 40
INFO 2018-02-02 10:30:45,187 - Calculating weight for id None
INFO 2018-02-02 10:30:45,190 - Updated weight for [4 : Mahesh Waikar] to 40
INFO 2018-02-02 10:30:48,282 - Calculating weight for id None
INFO 2018-02-02 10:30:48,286 - Updated weight for [4 : Mahesh Waikar] to 20
INFO 2018-02-02 10:30:50,615 - Calculating weight for id None
INFO 2018-02-02 10:30:50,621 - Updated weight for [4 : Mahesh Waikar] to 25
INFO 2018-02-02 10:31:10,319 - Calculating weight for id None
INFO 2018-02-02 10:31:10,336 - Updated weight for [4 : Mahesh Waikar] to 75
INFO 2018-02-02 10:31:31,618 - Calculating weight for id None
INFO 2018-02-02 10:31:31,635 - Updated weight for [4 : Mahesh Waikar] to 60
INFO 2018-02-02 10:31:33,798 - Calculating weight for id None
INFO 2018-02-02 10:31:33,805 - Updated weight for [4 : Mahesh Waikar] to 45
INFO 2018-02-02 10:31:35,720 - Calculating weight for id None
INFO 2018-02-02 10:31:35,727 - Updated weight for [4 : Mahesh Waikar] to 25
